<html>
<head>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css">
  <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js"></script>  
</head>
<body style="background-color:black;color:white;">

<div class="container">
<div class="row">
<div class="col-md-4" align="center">
<div class="container bg-secondary ">
<img src="reena.jpg" class="rounded-circle"  alt="reena" width="130" height="100"><br>
<p>reena valeker</p>
<p>reena.mscit15@gmail.com</p><br><br><br><br>
<h3 style="color:blue";>About</h3>
<p>I'm Reena.Full stack Website Devloper.<br>I enjoy my work.<br>I have one experience</p>
<p>
<br>
<br><br></p>

</div>
</div>
<div class="col-md-7 bg-secondary ">
<form action="" method="post" enctype="multipart / form-data">
<h3 style="color:blue">PersonalDetails</h3>
<div class="form-row">
<div class="col">
FirstName<input type="text" class="form-control" placeholder="Enter your name" name="fname"></div>
<div class="col">
Email <input type="email" placeholder="Enter your Email" class="form-control" name="email"></div>
</div>
<br>
<div class="form-row">
<div class="col">
 Phone No<input type="tel" placeholder="Enter your Mobile No" class="form-control" name="phone" > 
 </div>
<div class="col">
Website URL<input type="url" placeholder="Enter your website" class="form-control" name="website">
</div>
</div>
<br>
<br><h3 style="color:blue">Address</h3>
<div class="form-row">
<div class="col">Street<input type="text" class="form-control" name="stree" placeholder="Enter your street"></div>
<div class="col">city<input type="text" class="form-control" name="city" placeholder="Enter your city"></div>
</div>

<div class="form-row">
<div class="col">State<input type="text" class="form-control" name="state" placeholder="Enter your city "></div>
<div class="col">zipcode<input type="text" class="form-control" name="zipcode" placeholder="Enter your zipcode"></div>
</div>
<br>
<div align="right">
<button type="button" class="btn btn-dark">cancle</button>
<button type="button" class="btn btn-primary">submit</button>

</div>

		
</form>



</div>

</div>
</div>  
</body>
</html>