<html>
<head>
<meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css">
  <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js"></script>
  <style>
.checked {
  color: orange;
}
</style>
</head>
<body>
<div class="container">
<div class="row">
<table>
<div class="col-sm-5">
<div class="row">
<div class="column"><img src="tablate.jpg" width="200px" height="200px"></div>
<div class="column">Product code/Name Here<br>
Product catogary<br>
$199
<hr>
Product Description Here<br><br>
<button type="button" class="btn btn-danger">Add to card</button>
<button type="button" class="btn btn-primary">More Info</button><br>

<b>Rating:</b><span class="fa fa-star checked"></span>
<span class="fa fa-star checked"></span>
<span class="fa fa-star checked"></span>
<span class="fa fa-star"></span>
<span class="fa fa-star"></span>
</div>
</div>
</div>
</table>
<div class="col-sm-5">
<div class="row">
<div class="column"><img src="mobile.jpg" width="200px" height="200px"></div>
<div class="column">
Product code/Name Here<br>
Product catogary<br>
$50
<hr>
Product Description Here<br><br>
<button type="button" class="btn btn-danger" width="100px">Add to card</button>
<button type="button" class="btn btn-primary" width="100px">More Info</button><br>
<b>Rating:</b><span class="fa fa-star checked"></span>
<span class="fa fa-star checked"></span>
<span class="fa fa-star checked"></span>
<span class="fa fa-star"></span>
<span class="fa fa-star"></span>
</div></div>
</div>
</div>
</div>
</div>
<br>
<div class="container">
<div class="row">
<div class="col-sm-5">
<div class="row">
<div class="column"><img src="pc.jpg" width="180px" height="180px"></div>
<div class="column">Product code/Name Here<br>
Product catogary<br>
$299
<hr>
Product Description Here<br><br>
<button type="button" class="btn btn-danger">Add to card</button>
<button type="button" class="btn btn-primary">More Info</button><br>

<b>Rating:</b><span class="fa fa-star checked"></span>
<span class="fa fa-star checked"></span>
<span class="fa fa-star checked"></span>
<span class="fa fa-star"></span>
<span class="fa fa-star"></span>
</div>
</div>
</div>
<div class="col-sm-5">
<div class="row">
<div class="column"><img src="minilapy.jpg" width="180px" height="200px"></div>
<div class="column">
Product code/Name Here<br>
Product catogary<br>
$1000
<hr>
Product Description Here<br><br>
<button type="button" class="btn btn-danger" width="100px">Add to card</button>
<button type="button" class="btn btn-primary" width="100px">More Info</button><br>
<b>Rating:</b><span class="fa fa-star checked"></span>
<span class="fa fa-star checked"></span>
<span class="fa fa-star checked"></span>
<span class="fa fa-star"></span>
<span class="fa fa-star"></span>
</div></div>
</div>
</div>
</div>
</div>
<br>


</body>
</html>
